services:
  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - crm-server-network
    container_name: server_env

networks:
  crm-server-network: