name: CI/CD for server

on:
  push:
    branches: [action-controller]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: run env in Docker Compose
        run: |
          docker compose up -d
